### ISSUE TITLE
Error when running it on android emulator

### ISSUE THREAD

**Issue by brikendr** [thoqbk/rewebrtc#1]
I am experiencing the red error screen when trying to run the demo on my android emulator. I get the error "The development server returned response error code: 500"
"Unable to resolve module C:\\......\\rewebrtc\\node_modules\\engine.io-client\\lib\\transports\\index.j\\lib\\xmlhttprequrest.js\\" 

Any idea what the problem might be?

Thank you!

**Comment by thoqbk** [comment]
Hi, maybe it's version issue. Did you use npm or yarn to install node modules?
If you used npm the version of engine.io-client could not be compatible with others. Please see all modules and their versions I used in file ./yarn.lock.

**Comment by veedeo** [comment]
Same here, any fix for this?

**Comment by thoqbk** [comment]
@veedeo can you help to check the version of socket.io-client as well as engine.io-client in your node_modules?
In my project, they're socket.io-client@1.7.2 and engine.io-client@1.8.2.

**Comment by veedeo** [comment]
socket.io-client   "version": "1.7.2"
engine.io-client  "version": "1.8.2"

**Comment by thoqbk** [comment]
@veedeo can you share me the screen shot of issue in your local?

**Comment by veedeo** [comment]
Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  99.1%
(460/462)...(node:11988) UnhandledPromiseRejectionWarning: Unhandled
promise rejection (rejection id: 908): UnableToResolveError: Unable to
resolve module
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.j\lib\xmlhttprequest.js
from
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.js:
Directory
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.j\lib\xmlhttprequest.js
doesn't exist
(node:11988) DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that areBundling
`index.android.js`
  Analysing...

**Comment by thoqbk** [comment]
@veedeo I just updated my code. Can you try again?

**Comment by brikendr** [comment]
Hey @thoqbk, thanks for following up in the issue. I pulled the most recent version of the code in my local machine and still not able to get through that error! I used yarn to install the dependencies and also to startup the project "yarn" and then "yarn start", then i run the app in android simulator using "react-native run-android" command. 

The image below is a screenshot of the error. 
![screenshot_1491130185](https://cloud.githubusercontent.com/assets/22151612/24586517/74dc3210-17a3-11e7-9b4c-6259db839d7c.png)

**Comment by xmanemran** [comment]
Same problem hear. please save me. In my production fetch this problem.

**Comment by carrbrpoa** [comment]
I have the same problem. There seems to be a typo somewhere:

```
(...)
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.j\lib\xmlhttprequest.js
from
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.js
(...)
```

Look the missing **s** from `index.js` in the first line.

**Comment by BeThankxz** [comment]
me too .... :(

**Comment by constantinosergiou** [comment]
anyone fix it? nobody ? so we need to developer react native apps only on linux or mac ? this not good

**Comment by daviddang91** [comment]
I fixed. Open file \src\lib\services.js and replace `const socketIOClient = require('socket.io-client');` (line 34) to `const socketIOClient = require("socket.io-client/dist/socket.io");`

**Comment by yxwandroid** [comment]
me too!!
on  android emulator   
![image](https://user-images.githubusercontent.com/9635493/33984986-3a602f86-e0f4-11e7-9e0a-d48fdb4ade81.png)


Hopefully the author will match android

**Comment by pewh** [comment]
+1 I think example repo is broken. i have an issue `stream.reactTag` like above too

**Comment by thoqbk** [comment]
@pewh @yxwandroid 
Hi, may I know how to reproduce this error?

**Comment by pewh** [comment]
@thoqbk Hi. I'm using 2 genymotion instance, with Android Jelly Bean & Android Marshallow. On first simulator, I press button to enter the room. It should be show preview of webcam, but it's not!

On second simulator, I press button to enter the room, then this (second simulator) throw an error like picture above. I've try to debug, and the value of `localStream` at https://github.com/thoqbk/rewebrtc/blob/master/src/lib/services.js#L97 is `null`.

**Comment by uanthwal** [comment]
@veedeo : found solution to this problem? 
Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  99.1%
(460/462)...(node:11988) UnhandledPromiseRejectionWarning: Unhandled
promise rejection (rejection id: 908): UnableToResolveError: Unable to
resolve module
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.j\lib\xmlhttprequest.js
from
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.js:
Directory
C:\dev\repos\rewebrtc\node_modules\engine.io-client\lib\transports\index.j\lib\xmlhttprequest.js
doesn't exist
(node:11988) DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that areBundling
`index.android.js`
  Analysing...

**Comment by uanthwal** [comment]
@thoqbk : Hi, could please help in resolving the issue?

**Comment by haiquan33** [comment]
About the localStream is null, you must trigger getLocalStream ,after when the getLocalStream() has set the locaslStream variable  you can call Join() to start video call (service.js)

**Comment by andikare** [comment]
anyone figure out a solution ?

**Comment by YuePing1104** [comment]
Does anyone have the project up and running
